export const PROVINCES = [
  { code: "01", name: "Hà Nội" },
  { code: "02", name: "TP. Hồ Chí Minh" },
  { code: "03", name: "Hải Phòng" },
  { code: "04", name: "Đà Nẵng" },
  // { code: "05", name: "Hà Giang" },
  // { code: "06", name: "Cao Bằng" },
  // { code: "07", name: "Lai Châu" },
  // { code: "08", name: "Lào Cai" },
  // { code: "09", name: "Tuyên Quang" },
  // { code: "10", name: "Lạng Sơn" },
  // { code: "11", name: "Bắc Kạn" },
  // { code: "12", name: "Thái Nguyên" },
  // { code: "13", name: "Yên Bái" },
  // { code: "14", name: "Sơn La" },
  // { code: "15", name: "Phú Thọ" },
  // { code: "16", name: "Vĩnh Phúc" },
  // { code: "17", name: "Quảng Ninh" },
  // { code: "18", name: "Bắc Giang" },
  // { code: "19", name: "Bắc Ninh" },
  // { code: "20", name: "Hải Dương" },
  // { code: "21", name: "Hưng Yên" },
  // { code: "22", name: "Hòa Bình" },
  // { code: "23", name: "Hà Nam" },
  // { code: "24", name: "Nam Định" },
  // { code: "25", name: "Thái Bình" },
  // { code: "26", name: "Ninh Bình" },
  // { code: "27", name: "Thanh Hóa" },
  // { code: "28", name: "Nghệ An" },
  // { code: "29", name: "Hà Tĩnh" },
  // { code: "30", name: "Quảng Bình" },
  // { code: "31", name: "Quảng Trị" },
  // { code: "32", name: "Thừa Thiên Huế" },
  // { code: "33", name: "Quảng Nam" },
  // { code: "34", name: "Quảng Ngãi" },
  // { code: "35", name: "Kon Tum" },
  // { code: "36", name: "Bình Định" },
  // { code: "37", name: "Gia Lai" },
  // { code: "38", name: "Phú Yên" },
  // { code: "39", name: "Đắk Lắk" },
  // { code: "40", name: "Khánh Hòa" },
  // { code: "41", name: "Lâm Đồng" },
  // { code: "42", name: "Bình Phước" },
  // { code: "43", name: "Bình Dương" },
  // { code: "44", name: "Ninh Thuận" },
  // { code: "45", name: "Tây Ninh" },
  // { code: "46", name: "Bình Thuận" },
  // { code: "47", name: "Đồng Nai" },
  // { code: "48", name: "Long An" },
  // { code: "49", name: "Đồng Tháp" },
  // { code: "50", name: "An Giang" },
  // { code: "51", name: "Bà Rịa - Vũng Tàu" },
  // { code: "52", name: "Tiền Giang" },
  // { code: "53", name: "Kiên Giang" },
  // { code: "54", name: "Bến Tre" },
  // { code: "55", name: "Vĩnh Long" },
  // { code: "56", name: "Trà Vinh" },
  // { code: "57", name: "Sóc Trăng" },
  // { code: "58", name: "Bạc Liêu" },
  // { code: "59", name: "Cà Mau" },
  // { code: "60", name: "Điện Biên" },
  // { code: "61", name: "Đắk Nông" },
  // { code: "62", name: "Hậu Giang" },
  // { code: "63", name: "Cục Nhà trường - Bộ Quốc phòng" },
];
